version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/goodda-backend
    overwrite: yes

permissions:
  - object: /home/ubuntu/goodda-backend/
    owner: ubuntu
    group: ubuntu
    mode: 755

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root

#  ApplicationStart:
#    - location: scripts/run_new_was.sh
#      timeout: 180
#      runas: ubuntu
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: ubuntu
#    - location: scripts/switch.sh
#      timeout: 180
#      runas: ubuntu